
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 240


mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  publish_rate: 240

  left_wheel: 'WheelL_cont'
  right_wheel: 'WheelR_cont'

  # Wheel separation and diameter. 
  wheel_separation : 0.53
  wheel_radius : 0.32

  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0] 

  cmd_vel_timeout: 0.25

  publish_cmd: true

  base_frame_id: base_link

   # Velocity and acceleration limits for the robot
  linear:
   x:
     has_velocity_limits    : true
     max_velocity           : 5  # m/s
     has_acceleration_limits: true
     max_acceleration       : 2   # m/s^2
     has_jerk_limits        : true
     max_jerk               : 5.0 # m/s^3
  angular:
   z:
     has_velocity_limits    : true
     max_velocity           : 2   # rad/s
     has_acceleration_limits: true
     max_acceleration       : 2   # rad/s^2
     has_jerk_limits        : true
     max_jerk               : 2.5 #rad/s^3
